---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8s-bindplane-com-v1alpha1-bindplane
  failurePolicy: Fail
  name: mbindplane.kb.io
  rules:
  - apiGroups:
    - k8s.bindplane.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bindplanes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-bindplane-com-v1alpha1-bindplane
  failurePolicy: Fail
  name: vbindplane.kb.io
  rules:
  - apiGroups:
    - k8s.bindplane.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bindplanes
  sideEffects: None
