---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bindplane.com
  resources:
  - bindplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bindplane.com
  resources:
  - bindplanes/finalizers
  verbs:
  - update
- apiGroups:
  - bindplane.com
  resources:
  - bindplanes/status
  verbs:
  - get
  - patch
  - update
