//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1 "k8s.io/api/apps/v1"
	"k8s.io/api/autoscaling/v2"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedCacheConfig) DeepCopyInto(out *AdvancedCacheConfig) {
	*out = *in
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(AdvancedCacheRedisConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedCacheConfig.
func (in *AdvancedCacheConfig) DeepCopy() *AdvancedCacheConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedCacheRedisConfig) DeepCopyInto(out *AdvancedCacheRedisConfig) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(AdvancedCacheRedisTLSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedCacheRedisConfig.
func (in *AdvancedCacheRedisConfig) DeepCopy() *AdvancedCacheRedisConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedCacheRedisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedCacheRedisTLSConfig) DeepCopyInto(out *AdvancedCacheRedisTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedCacheRedisTLSConfig.
func (in *AdvancedCacheRedisTLSConfig) DeepCopy() *AdvancedCacheRedisTLSConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedCacheRedisTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedConfig) DeepCopyInto(out *AdvancedConfig) {
	*out = *in
	if in.Store != nil {
		in, out := &in.Store, &out.Store
		*out = new(AdvancedStoreConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(AdvancedServerConfig)
		**out = **in
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(AdvancedCacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(AdvancedRolloutConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedConfig.
func (in *AdvancedConfig) DeepCopy() *AdvancedConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedRolloutConfig) DeepCopyInto(out *AdvancedRolloutConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedRolloutConfig.
func (in *AdvancedRolloutConfig) DeepCopy() *AdvancedRolloutConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedRolloutConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedServerConfig) DeepCopyInto(out *AdvancedServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedServerConfig.
func (in *AdvancedServerConfig) DeepCopy() *AdvancedServerConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedStoreConfig) DeepCopyInto(out *AdvancedStoreConfig) {
	*out = *in
	if in.Stats != nil {
		in, out := &in.Stats, &out.Stats
		*out = new(AdvancedStoreStatsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedStoreConfig.
func (in *AdvancedStoreConfig) DeepCopy() *AdvancedStoreConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedStoreStatsConfig) DeepCopyInto(out *AdvancedStoreStatsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedStoreStatsConfig.
func (in *AdvancedStoreStatsConfig) DeepCopy() *AdvancedStoreStatsConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedStoreStatsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDuplicationPreventionConfig) DeepCopyInto(out *AgentDuplicationPreventionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDuplicationPreventionConfig.
func (in *AgentDuplicationPreventionConfig) DeepCopy() *AgentDuplicationPreventionConfig {
	if in == nil {
		return nil
	}
	out := new(AgentDuplicationPreventionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentVersionsConfig) DeepCopyInto(out *AgentVersionsConfig) {
	*out = *in
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentVersionsConfig.
func (in *AgentVersionsConfig) DeepCopy() *AgentVersionsConfig {
	if in == nil {
		return nil
	}
	out := new(AgentVersionsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentsAuthConfig) DeepCopyInto(out *AgentsAuthConfig) {
	*out = *in
	if in.SecretKey != nil {
		in, out := &in.SecretKey, &out.SecretKey
		*out = new(AgentsAuthSecretKeyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(AgentsAuthOAuthConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentsAuthConfig.
func (in *AgentsAuthConfig) DeepCopy() *AgentsAuthConfig {
	if in == nil {
		return nil
	}
	out := new(AgentsAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentsAuthOAuthConfig) DeepCopyInto(out *AgentsAuthOAuthConfig) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredClaims != nil {
		in, out := &in.RequiredClaims, &out.RequiredClaims
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredScopes != nil {
		in, out := &in.RequiredScopes, &out.RequiredScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentsAuthOAuthConfig.
func (in *AgentsAuthOAuthConfig) DeepCopy() *AgentsAuthOAuthConfig {
	if in == nil {
		return nil
	}
	out := new(AgentsAuthOAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentsAuthSecretKeyConfig) DeepCopyInto(out *AgentsAuthSecretKeyConfig) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentsAuthSecretKeyConfig.
func (in *AgentsAuthSecretKeyConfig) DeepCopy() *AgentsAuthSecretKeyConfig {
	if in == nil {
		return nil
	}
	out := new(AgentsAuthSecretKeyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentsConfig) DeepCopyInto(out *AgentsConfig) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AgentsAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RebalancePercentage != nil {
		in, out := &in.RebalancePercentage, &out.RebalancePercentage
		*out = new(int)
		**out = **in
	}
	if in.RebalanceJitter != nil {
		in, out := &in.RebalanceJitter, &out.RebalanceJitter
		*out = new(int)
		**out = **in
	}
	if in.DuplicationPrevention != nil {
		in, out := &in.DuplicationPrevention, &out.DuplicationPrevention
		*out = new(AgentDuplicationPreventionConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentsConfig.
func (in *AgentsConfig) DeepCopy() *AgentsConfig {
	if in == nil {
		return nil
	}
	out := new(AgentsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsConfig) DeepCopyInto(out *AnalyticsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsConfig.
func (in *AnalyticsConfig) DeepCopy() *AnalyticsConfig {
	if in == nil {
		return nil
	}
	out := new(AnalyticsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicConfig) DeepCopyInto(out *AnthropicConfig) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicConfig.
func (in *AnthropicConfig) DeepCopy() *AnthropicConfig {
	if in == nil {
		return nil
	}
	out := new(AnthropicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditTrailConfig) DeepCopyInto(out *AuditTrailConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditTrailConfig.
func (in *AuditTrailConfig) DeepCopy() *AuditTrailConfig {
	if in == nil {
		return nil
	}
	out := new(AuditTrailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth0Config) DeepCopyInto(out *Auth0Config) {
	*out = *in
	if in.ManagementClientSecretSecretRef != nil {
		in, out := &in.ManagementClientSecretSecretRef, &out.ManagementClientSecretSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SSO != nil {
		in, out := &in.SSO, &out.SSO
		*out = new(Auth0SSOConfig)
		**out = **in
	}
	if in.WIF != nil {
		in, out := &in.WIF, &out.WIF
		*out = new(Auth0WIFConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth0Config.
func (in *Auth0Config) DeepCopy() *Auth0Config {
	if in == nil {
		return nil
	}
	out := new(Auth0Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth0SSOConfig) DeepCopyInto(out *Auth0SSOConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth0SSOConfig.
func (in *Auth0SSOConfig) DeepCopy() *Auth0SSOConfig {
	if in == nil {
		return nil
	}
	out := new(Auth0SSOConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth0WIFConfig) DeepCopyInto(out *Auth0WIFConfig) {
	*out = *in
	if in.ClientSecretSecretRef != nil {
		in, out := &in.ClientSecretSecretRef, &out.ClientSecretSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth0WIFConfig.
func (in *Auth0WIFConfig) DeepCopy() *Auth0WIFConfig {
	if in == nil {
		return nil
	}
	out := new(Auth0WIFConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionSecretSecretRef != nil {
		in, out := &in.SessionSecretSecretRef, &out.SessionSecretSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LDAP != nil {
		in, out := &in.LDAP, &out.LDAP
		*out = new(LDAPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth0 != nil {
		in, out := &in.Auth0, &out.Auth0
		*out = new(Auth0Config)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bindplane) DeepCopyInto(out *Bindplane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bindplane.
func (in *Bindplane) DeepCopy() *Bindplane {
	if in == nil {
		return nil
	}
	out := new(Bindplane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Bindplane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindplaneComponentSpec) DeepCopyInto(out *BindplaneComponentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MinReadySeconds != nil {
		in, out := &in.MinReadySeconds, &out.MinReadySeconds
		*out = new(int32)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(appsv1.DeploymentStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(NodeAutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindplaneComponentSpec.
func (in *BindplaneComponentSpec) DeepCopy() *BindplaneComponentSpec {
	if in == nil {
		return nil
	}
	out := new(BindplaneComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindplaneConfigSpec) DeepCopyInto(out *BindplaneConfigSpec) {
	*out = *in
	if in.LicenseSecretRef != nil {
		in, out := &in.LicenseSecretRef, &out.LicenseSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Store.DeepCopyInto(&out.Store)
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(TracingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AuditTrail != nil {
		in, out := &in.AuditTrail, &out.AuditTrail
		*out = new(AuditTrailConfig)
		**out = **in
	}
	if in.TSDB != nil {
		in, out := &in.TSDB, &out.TSDB
		*out = new(TSDBConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Nats != nil {
		in, out := &in.Nats, &out.Nats
		*out = new(NatsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Profiling != nil {
		in, out := &in.Profiling, &out.Profiling
		*out = new(ProfilingConfig)
		**out = **in
	}
	if in.Pprof != nil {
		in, out := &in.Pprof, &out.Pprof
		*out = new(PprofConfig)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(StatusConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EventBus != nil {
		in, out := &in.EventBus, &out.EventBus
		*out = new(EventBusConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Analytics != nil {
		in, out := &in.Analytics, &out.Analytics
		*out = new(AnalyticsConfig)
		**out = **in
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Advanced != nil {
		in, out := &in.Advanced, &out.Advanced
		*out = new(AdvancedConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = new(AgentsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentVersions != nil {
		in, out := &in.AgentVersions, &out.AgentVersions
		*out = new(AgentVersionsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SaaS != nil {
		in, out := &in.SaaS, &out.SaaS
		*out = new(SaaSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EncryptionProvider != nil {
		in, out := &in.EncryptionProvider, &out.EncryptionProvider
		*out = new(EncryptionProviderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(FeaturesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = new(ErrorsConfig)
		**out = **in
	}
	if in.LLM != nil {
		in, out := &in.LLM, &out.LLM
		*out = new(LLMConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = new(QuotasConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindplaneConfigSpec.
func (in *BindplaneConfigSpec) DeepCopy() *BindplaneConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BindplaneConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindplaneJobsComponentSpec) DeepCopyInto(out *BindplaneJobsComponentSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindplaneJobsComponentSpec.
func (in *BindplaneJobsComponentSpec) DeepCopy() *BindplaneJobsComponentSpec {
	if in == nil {
		return nil
	}
	out := new(BindplaneJobsComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindplaneJobsMigrateComponentSpec) DeepCopyInto(out *BindplaneJobsMigrateComponentSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindplaneJobsMigrateComponentSpec.
func (in *BindplaneJobsMigrateComponentSpec) DeepCopy() *BindplaneJobsMigrateComponentSpec {
	if in == nil {
		return nil
	}
	out := new(BindplaneJobsMigrateComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindplaneList) DeepCopyInto(out *BindplaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Bindplane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindplaneList.
func (in *BindplaneList) DeepCopy() *BindplaneList {
	if in == nil {
		return nil
	}
	out := new(BindplaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BindplaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindplaneSpec) DeepCopyInto(out *BindplaneSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.Bindplane.DeepCopyInto(&out.Bindplane)
	if in.BindplaneJobs != nil {
		in, out := &in.BindplaneJobs, &out.BindplaneJobs
		*out = new(BindplaneJobsComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BindplaneJobsMigrate != nil {
		in, out := &in.BindplaneJobsMigrate, &out.BindplaneJobsMigrate
		*out = new(BindplaneJobsMigrateComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TransformAgent != nil {
		in, out := &in.TransformAgent, &out.TransformAgent
		*out = new(TransformAgentComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TSDB != nil {
		in, out := &in.TSDB, &out.TSDB
		*out = new(TSDBComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Nats != nil {
		in, out := &in.Nats, &out.Nats
		*out = new(NatsComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OpAMP != nil {
		in, out := &in.OpAMP, &out.OpAMP
		*out = new(OpAMPComponentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindplaneSpec.
func (in *BindplaneSpec) DeepCopy() *BindplaneSpec {
	if in == nil {
		return nil
	}
	out := new(BindplaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindplaneStatus) DeepCopyInto(out *BindplaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindplaneStatus.
func (in *BindplaneStatus) DeepCopy() *BindplaneStatus {
	if in == nil {
		return nil
	}
	out := new(BindplaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerTLSIssuerRef) DeepCopyInto(out *CertManagerTLSIssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerTLSIssuerRef.
func (in *CertManagerTLSIssuerRef) DeepCopy() *CertManagerTLSIssuerRef {
	if in == nil {
		return nil
	}
	out := new(CertManagerTLSIssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionProviderConfig) DeepCopyInto(out *EncryptionProviderConfig) {
	*out = *in
	if in.GoogleKMS != nil {
		in, out := &in.GoogleKMS, &out.GoogleKMS
		*out = new(GoogleKMSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionProviderConfig.
func (in *EncryptionProviderConfig) DeepCopy() *EncryptionProviderConfig {
	if in == nil {
		return nil
	}
	out := new(EncryptionProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorsConfig) DeepCopyInto(out *ErrorsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorsConfig.
func (in *ErrorsConfig) DeepCopy() *ErrorsConfig {
	if in == nil {
		return nil
	}
	out := new(ErrorsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBusConfig) DeepCopyInto(out *EventBusConfig) {
	*out = *in
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(EventBusHealthConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBusConfig.
func (in *EventBusConfig) DeepCopy() *EventBusConfig {
	if in == nil {
		return nil
	}
	out := new(EventBusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBusHealthConfig) DeepCopyInto(out *EventBusHealthConfig) {
	*out = *in
	if in.RequiredHosts != nil {
		in, out := &in.RequiredHosts, &out.RequiredHosts
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBusHealthConfig.
func (in *EventBusHealthConfig) DeepCopy() *EventBusHealthConfig {
	if in == nil {
		return nil
	}
	out := new(EventBusHealthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureOverridesConfig) DeepCopyInto(out *FeatureOverridesConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureOverridesConfig.
func (in *FeatureOverridesConfig) DeepCopy() *FeatureOverridesConfig {
	if in == nil {
		return nil
	}
	out := new(FeatureOverridesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesConfig) DeepCopyInto(out *FeaturesConfig) {
	*out = *in
	if in.PostHog != nil {
		in, out := &in.PostHog, &out.PostHog
		*out = new(PostHogConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(FeatureOverridesConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesConfig.
func (in *FeaturesConfig) DeepCopy() *FeaturesConfig {
	if in == nil {
		return nil
	}
	out := new(FeaturesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeminiConfig) DeepCopyInto(out *GeminiConfig) {
	*out = *in
	if in.VectorSearchRedis != nil {
		in, out := &in.VectorSearchRedis, &out.VectorSearchRedis
		*out = new(VectorSearchRedisConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeminiConfig.
func (in *GeminiConfig) DeepCopy() *GeminiConfig {
	if in == nil {
		return nil
	}
	out := new(GeminiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleKMSConfig) DeepCopyInto(out *GoogleKMSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleKMSConfig.
func (in *GoogleKMSConfig) DeepCopy() *GoogleKMSConfig {
	if in == nil {
		return nil
	}
	out := new(GoogleKMSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPConfig) DeepCopyInto(out *LDAPConfig) {
	*out = *in
	if in.BindUserSecretRef != nil {
		in, out := &in.BindUserSecretRef, &out.BindUserSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.BindPasswordSecretRef != nil {
		in, out := &in.BindPasswordSecretRef, &out.BindPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(LDAPTLSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPConfig.
func (in *LDAPConfig) DeepCopy() *LDAPConfig {
	if in == nil {
		return nil
	}
	out := new(LDAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPTLSConfig) DeepCopyInto(out *LDAPTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPTLSConfig.
func (in *LDAPTLSConfig) DeepCopy() *LDAPTLSConfig {
	if in == nil {
		return nil
	}
	out := new(LDAPTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMConfig) DeepCopyInto(out *LLMConfig) {
	*out = *in
	if in.Gemini != nil {
		in, out := &in.Gemini, &out.Gemini
		*out = new(GeminiConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Langsmith != nil {
		in, out := &in.Langsmith, &out.Langsmith
		*out = new(LangsmithConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = new(OpenAIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Anthropic != nil {
		in, out := &in.Anthropic, &out.Anthropic
		*out = new(AnthropicConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMConfig.
func (in *LLMConfig) DeepCopy() *LLMConfig {
	if in == nil {
		return nil
	}
	out := new(LLMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LangsmithConfig) DeepCopyInto(out *LangsmithConfig) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LangsmithConfig.
func (in *LangsmithConfig) DeepCopy() *LangsmithConfig {
	if in == nil {
		return nil
	}
	out := new(LangsmithConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(LoggingOTLPConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingOTLPConfig) DeepCopyInto(out *LoggingOTLPConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingOTLPConfig.
func (in *LoggingOTLPConfig) DeepCopy() *LoggingOTLPConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingOTLPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfig) DeepCopyInto(out *MetricsConfig) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(MetricsPrometheusConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(MetricsOTLPConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfig.
func (in *MetricsConfig) DeepCopy() *MetricsConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsOTLPConfig) DeepCopyInto(out *MetricsOTLPConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsOTLPConfig.
func (in *MetricsOTLPConfig) DeepCopy() *MetricsOTLPConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsOTLPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsPrometheusConfig) DeepCopyInto(out *MetricsPrometheusConfig) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsPrometheusConfig.
func (in *MetricsPrometheusConfig) DeepCopy() *MetricsPrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsPrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsComponentSpec) DeepCopyInto(out *NatsComponentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsComponentSpec.
func (in *NatsComponentSpec) DeepCopy() *NatsComponentSpec {
	if in == nil {
		return nil
	}
	out := new(NatsComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsConfig) DeepCopyInto(out *NatsConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(NatsTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsConfig.
func (in *NatsConfig) DeepCopy() *NatsConfig {
	if in == nil {
		return nil
	}
	out := new(NatsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NatsTLSConfig) DeepCopyInto(out *NatsTLSConfig) {
	*out = *in
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerTLSIssuerRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NatsTLSConfig.
func (in *NatsTLSConfig) DeepCopy() *NatsTLSConfig {
	if in == nil {
		return nil
	}
	out := new(NatsTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(NetworkTLSConfig)
		**out = **in
	}
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = new(NetworkRateLimitsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRateLimitsConfig) DeepCopyInto(out *NetworkRateLimitsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRateLimitsConfig.
func (in *NetworkRateLimitsConfig) DeepCopy() *NetworkRateLimitsConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkRateLimitsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkTLSConfig) DeepCopyInto(out *NetworkTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkTLSConfig.
func (in *NetworkTLSConfig) DeepCopy() *NetworkTLSConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAutoscalingSpec) DeepCopyInto(out *NodeAutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]v2.MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(v2.HorizontalPodAutoscalerBehavior)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAutoscalingSpec.
func (in *NodeAutoscalingSpec) DeepCopy() *NodeAutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(NodeAutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfig) DeepCopyInto(out *OIDCConfig) {
	*out = *in
	if in.ClientIDSecretRef != nil {
		in, out := &in.ClientIDSecretRef, &out.ClientIDSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSecretSecretRef != nil {
		in, out := &in.ClientSecretSecretRef, &out.ClientSecretSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfig.
func (in *OIDCConfig) DeepCopy() *OIDCConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpAMPComponentSpec) DeepCopyInto(out *OpAMPComponentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MinReadySeconds != nil {
		in, out := &in.MinReadySeconds, &out.MinReadySeconds
		*out = new(int32)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(appsv1.DeploymentStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(NodeAutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxSimultaneousConnections != nil {
		in, out := &in.MaxSimultaneousConnections, &out.MaxSimultaneousConnections
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpAMPComponentSpec.
func (in *OpAMPComponentSpec) DeepCopy() *OpAMPComponentSpec {
	if in == nil {
		return nil
	}
	out := new(OpAMPComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIConfig) DeepCopyInto(out *OpenAIConfig) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIConfig.
func (in *OpenAIConfig) DeepCopy() *OpenAIConfig {
	if in == nil {
		return nil
	}
	out := new(OpenAIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTemplateSpec) DeepCopyInto(out *PodTemplateSpec) {
	*out = *in
	in.PodTemplateSpec.DeepCopyInto(&out.PodTemplateSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTemplateSpec.
func (in *PodTemplateSpec) DeepCopy() *PodTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PodTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostHogConfig) DeepCopyInto(out *PostHogConfig) {
	*out = *in
	if in.ProjectAPIKeySecretRef != nil {
		in, out := &in.ProjectAPIKeySecretRef, &out.ProjectAPIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PersonalAPIKeySecretRef != nil {
		in, out := &in.PersonalAPIKeySecretRef, &out.PersonalAPIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostHogConfig.
func (in *PostHogConfig) DeepCopy() *PostHogConfig {
	if in == nil {
		return nil
	}
	out := new(PostHogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresConfig) DeepCopyInto(out *PostgresConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(PostgresTLSConfig)
		**out = **in
	}
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxIdleConnections != nil {
		in, out := &in.MaxIdleConnections, &out.MaxIdleConnections
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresConfig.
func (in *PostgresConfig) DeepCopy() *PostgresConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresTLSConfig) DeepCopyInto(out *PostgresTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresTLSConfig.
func (in *PostgresTLSConfig) DeepCopy() *PostgresTLSConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PprofConfig) DeepCopyInto(out *PprofConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PprofConfig.
func (in *PprofConfig) DeepCopy() *PprofConfig {
	if in == nil {
		return nil
	}
	out := new(PprofConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingConfig) DeepCopyInto(out *ProfilingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingConfig.
func (in *ProfilingConfig) DeepCopy() *ProfilingConfig {
	if in == nil {
		return nil
	}
	out := new(ProfilingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotasConfig) DeepCopyInto(out *QuotasConfig) {
	*out = *in
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = new(QuotasTierConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotasConfig.
func (in *QuotasConfig) DeepCopy() *QuotasConfig {
	if in == nil {
		return nil
	}
	out := new(QuotasConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotasTierConfig) DeepCopyInto(out *QuotasTierConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotasTierConfig.
func (in *QuotasTierConfig) DeepCopy() *QuotasTierConfig {
	if in == nil {
		return nil
	}
	out := new(QuotasTierConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SaaSConfig) DeepCopyInto(out *SaaSConfig) {
	*out = *in
	if in.LicenseServerAPIKeySecretRef != nil {
		in, out := &in.LicenseServerAPIKeySecretRef, &out.LicenseServerAPIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Stripe != nil {
		in, out := &in.Stripe, &out.Stripe
		*out = new(SaaSStripeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SaaSConfig.
func (in *SaaSConfig) DeepCopy() *SaaSConfig {
	if in == nil {
		return nil
	}
	out := new(SaaSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SaaSStripeConfig) DeepCopyInto(out *SaaSStripeConfig) {
	*out = *in
	if in.SecretKeySecretRef != nil {
		in, out := &in.SecretKeySecretRef, &out.SecretKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PublishableKeySecretRef != nil {
		in, out := &in.PublishableKeySecretRef, &out.PublishableKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.WebhookSecretSecretRef != nil {
		in, out := &in.WebhookSecretSecretRef, &out.WebhookSecretSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.GrowthPlanIDs != nil {
		in, out := &in.GrowthPlanIDs, &out.GrowthPlanIDs
		*out = new(SaaSStripeGrowthPlanIDsConfig)
		**out = **in
	}
	if in.GrowthPlanMeterNames != nil {
		in, out := &in.GrowthPlanMeterNames, &out.GrowthPlanMeterNames
		*out = new(SaaSStripeGrowthPlanMeterNamesConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SaaSStripeConfig.
func (in *SaaSStripeConfig) DeepCopy() *SaaSStripeConfig {
	if in == nil {
		return nil
	}
	out := new(SaaSStripeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SaaSStripeGrowthPlanIDsConfig) DeepCopyInto(out *SaaSStripeGrowthPlanIDsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SaaSStripeGrowthPlanIDsConfig.
func (in *SaaSStripeGrowthPlanIDsConfig) DeepCopy() *SaaSStripeGrowthPlanIDsConfig {
	if in == nil {
		return nil
	}
	out := new(SaaSStripeGrowthPlanIDsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SaaSStripeGrowthPlanMeterNamesConfig) DeepCopyInto(out *SaaSStripeGrowthPlanMeterNamesConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SaaSStripeGrowthPlanMeterNamesConfig.
func (in *SaaSStripeGrowthPlanMeterNamesConfig) DeepCopy() *SaaSStripeGrowthPlanMeterNamesConfig {
	if in == nil {
		return nil
	}
	out := new(SaaSStripeGrowthPlanMeterNamesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusConfig) DeepCopyInto(out *StatusConfig) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeysSecretRef != nil {
		in, out := &in.KeysSecretRef, &out.KeysSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusConfig.
func (in *StatusConfig) DeepCopy() *StatusConfig {
	if in == nil {
		return nil
	}
	out := new(StatusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(VolumeClaimTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreConfig) DeepCopyInto(out *StoreConfig) {
	*out = *in
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SummaryRollupRetentionDays != nil {
		in, out := &in.SummaryRollupRetentionDays, &out.SummaryRollupRetentionDays
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreConfig.
func (in *StoreConfig) DeepCopy() *StoreConfig {
	if in == nil {
		return nil
	}
	out := new(StoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSDBComponentSpec) DeepCopyInto(out *TSDBComponentSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TSDBTLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSDBComponentSpec.
func (in *TSDBComponentSpec) DeepCopy() *TSDBComponentSpec {
	if in == nil {
		return nil
	}
	out := new(TSDBComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSDBConfig) DeepCopyInto(out *TSDBConfig) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(TSDBRemoteConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TSDBTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSDBConfig.
func (in *TSDBConfig) DeepCopy() *TSDBConfig {
	if in == nil {
		return nil
	}
	out := new(TSDBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSDBRemoteConfig) DeepCopyInto(out *TSDBRemoteConfig) {
	*out = *in
	if in.RemoteWrite != nil {
		in, out := &in.RemoteWrite, &out.RemoteWrite
		*out = new(TSDBRemoteWriteConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSDBRemoteConfig.
func (in *TSDBRemoteConfig) DeepCopy() *TSDBRemoteConfig {
	if in == nil {
		return nil
	}
	out := new(TSDBRemoteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSDBRemoteWriteConfig) DeepCopyInto(out *TSDBRemoteWriteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSDBRemoteWriteConfig.
func (in *TSDBRemoteWriteConfig) DeepCopy() *TSDBRemoteWriteConfig {
	if in == nil {
		return nil
	}
	out := new(TSDBRemoteWriteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSDBTLSConfig) DeepCopyInto(out *TSDBTLSConfig) {
	*out = *in
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerTLSIssuerRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSDBTLSConfig.
func (in *TSDBTLSConfig) DeepCopy() *TSDBTLSConfig {
	if in == nil {
		return nil
	}
	out := new(TSDBTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfig) DeepCopyInto(out *TracingConfig) {
	*out = *in
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(TracingOTLPConfig)
		**out = **in
	}
	if in.Honeycomb != nil {
		in, out := &in.Honeycomb, &out.Honeycomb
		*out = new(TracingHoneycombConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfig.
func (in *TracingConfig) DeepCopy() *TracingConfig {
	if in == nil {
		return nil
	}
	out := new(TracingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingHoneycombConfig) DeepCopyInto(out *TracingHoneycombConfig) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingHoneycombConfig.
func (in *TracingHoneycombConfig) DeepCopy() *TracingHoneycombConfig {
	if in == nil {
		return nil
	}
	out := new(TracingHoneycombConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingOTLPConfig) DeepCopyInto(out *TracingOTLPConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingOTLPConfig.
func (in *TracingOTLPConfig) DeepCopy() *TracingOTLPConfig {
	if in == nil {
		return nil
	}
	out := new(TracingOTLPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformAgentComponentSpec) DeepCopyInto(out *TransformAgentComponentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TransformAgentTLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformAgentComponentSpec.
func (in *TransformAgentComponentSpec) DeepCopy() *TransformAgentComponentSpec {
	if in == nil {
		return nil
	}
	out := new(TransformAgentComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformAgentTLSConfig) DeepCopyInto(out *TransformAgentTLSConfig) {
	*out = *in
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerTLSIssuerRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformAgentTLSConfig.
func (in *TransformAgentTLSConfig) DeepCopy() *TransformAgentTLSConfig {
	if in == nil {
		return nil
	}
	out := new(TransformAgentTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorSearchRedisConfig) DeepCopyInto(out *VectorSearchRedisConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorSearchRedisConfig.
func (in *VectorSearchRedisConfig) DeepCopy() *VectorSearchRedisConfig {
	if in == nil {
		return nil
	}
	out := new(VectorSearchRedisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeClaimTemplate) DeepCopyInto(out *VolumeClaimTemplate) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(metav1.ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeClaimTemplate.
func (in *VolumeClaimTemplate) DeepCopy() *VolumeClaimTemplate {
	if in == nil {
		return nil
	}
	out := new(VolumeClaimTemplate)
	in.DeepCopyInto(out)
	return out
}
