name: E2E Bindplane

on:
  workflow_dispatch:

jobs:
  test-e2e-bindplane:
    name: Test E2E Bindplane
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run Bindplane e2e tests
        env:
          KIND_K8S_VERSION: "1.34.0"
          CERT_MANAGER_VERSION: latest
          BINDPLANE_LICENSE: ${{ secrets.BINDPLANE_LICENSE }}
        run: |
          if [ -z "${BINDPLANE_LICENSE}" ]; then
            echo "BINDPLANE_LICENSE is not configured."
            exit 1
          fi
          go mod tidy
          make test-e2e-bindplane
